//
//  HijinnksStyleKit.h
//  Hijinnks
//
//  Created by Adebayo Ijidakinro on 3/4/17.
//  Copyright (c) 2017 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface HijinnksStyleKit : NSObject

// Drawing Methods
+ (void)drawMapButtonWithFrame: (CGRect)frame;

@end
